# Generated by Django 4.2.1 on 2023-05-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('SSN', models.CharField(max_length=14)),
                ('student_id', models.IntegerField()),
                ('Gpa', models.DecimalField(decimal_places=4, max_digits=5)),
                ('Level', models.IntegerField()),
                ('Department', models.CharField(max_length=255)),
                ('Status', models.IntegerField(default=0)),
                ('Gender', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('SSN', 'student_id')},
            },
        ),
    ]
